# Generated by Django 6.0.3 on 2026-03-21 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], help_text='Mobile money provider', max_length=10, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction reference from mobile money SMS', max_length=100, null=True, verbose_name='transaction ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the payment', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the payment was verified or rejected', null=True, verbose_name='verified at')),
                ('booking', models.OneToOneField(help_text='The booking associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'), models.Index(fields=['payment_method', 'status'], name='payments_pa_payment_11cbdd_idx')],
            },
        ),
    ]
