# Generated by Django 6.0.3 on 2026-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.ImageField(blank=True, help_text='Upload a clear image of your identification document', null=True, upload_to='ids/%Y/%m/%d/', verbose_name='ID document'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='Unique identification number', max_length=100, null=True, unique=True, verbose_name='ID number'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('student_id', 'Student ID')], help_text='Type of identification document', max_length=20, null=True, verbose_name='ID type'),
        ),
    ]
