# Generated by Django 6.0.3 on 2026-03-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apartment_apartmentmedia_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apartment',
            name='users_apart_owner_i_e15ac2_idx',
        ),
        migrations.RemoveIndex(
            model_name='apartment',
            name='users_apart_distric_d3affa_idx',
        ),
        migrations.RemoveIndex(
            model_name='apartment',
            name='users_apart_availab_8dd48e_idx',
        ),
        migrations.RemoveIndex(
            model_name='apartmentmedia',
            name='users_apart_apartme_118de6_idx',
        ),
        migrations.RemoveIndex(
            model_name='apartmentmedia',
            name='users_apart_media_t_001887_idx',
        ),
        migrations.RemoveField(
            model_name='apartmentmedia',
            name='apartment',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='ApartmentMedia',
        ),
    ]
