# Generated by Django 6.0.3 on 2026-03-21 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the apartment listing', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Detailed description of the apartment', verbose_name='description')),
                ('price_daily', models.DecimalField(decimal_places=2, help_text='Price per night', max_digits=10, verbose_name='daily price')),
                ('price_weekly', models.DecimalField(blank=True, decimal_places=2, help_text='Price per week (optional)', max_digits=10, null=True, verbose_name='weekly price')),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Price per month (optional)', max_digits=10, null=True, verbose_name='monthly price')),
                ('district', models.CharField(help_text='District where the apartment is located', max_length=100, verbose_name='district')),
                ('sector', models.CharField(help_text='Sector or neighborhood', max_length=100, verbose_name='sector')),
                ('address', models.TextField(help_text='Full street address', verbose_name='address')),
                ('nearby_landmarks', models.TextField(blank=True, help_text='Notable landmarks near the apartment', verbose_name='nearby landmarks')),
                ('is_furnished', models.BooleanField(default=False, help_text='Whether the apartment comes with furniture', verbose_name='furnished')),
                ('has_wifi', models.BooleanField(default=False, help_text='Whether WiFi is available', verbose_name='WiFi')),
                ('has_parking', models.BooleanField(default=False, help_text='Whether parking is available', verbose_name='parking')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the apartment has been verified by admin', verbose_name='verified')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', help_text='Current availability status of the apartment', max_length=20, verbose_name='availability status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(help_text='Owner of the apartment', limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apartment',
                'verbose_name_plural': 'apartments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload image or video file', upload_to='apartments/media/%Y/%m/%d/', verbose_name='file')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Type of media file', max_length=10, verbose_name='media type')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('apartment', models.ForeignKey(help_text='Apartment this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='apartments.apartment')),
            ],
            options={
                'verbose_name': 'apartment media',
                'verbose_name_plural': 'apartment media',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['owner', 'created_at'], name='apartments__owner_i_72e9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['district', 'sector'], name='apartments__distric_26859a_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['availability_status'], name='apartments__availab_d1e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentmedia',
            index=models.Index(fields=['apartment', 'uploaded_at'], name='apartments__apartme_215f35_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentmedia',
            index=models.Index(fields=['media_type'], name='apartments__media_t_16b38a_idx'),
        ),
    ]
