# Generated by Django 6.0.3 on 2026-04-10 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='payment_method',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], default='mtn', help_text='Preferred mobile money provider for receiving payments', max_length=10, verbose_name='payment method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='payment_number',
            field=models.CharField(default='0000000000', help_text='Phone number for receiving mobile money payments', max_length=20, verbose_name='payment number'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['payment_method'], name='apartments__payment_8a7900_idx'),
        ),
    ]
