# Generated by Django 6.0.3 on 2026-04-11 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_payment_method_apartment_payment_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of times this apartment has been viewed', verbose_name='views count'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['-views_count'], name='apartments__views_c_666474_idx'),
        ),
    ]
