# Generated by Django 6.0.3 on 2026-03-21 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], help_text='Rating from 1 to 5 stars', verbose_name='rating')),
                ('comment', models.TextField(blank=True, help_text='Detailed review comment (optional)', verbose_name='comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('apartment', models.ForeignKey(help_text='Apartment being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apartments.apartment')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['apartment', 'rating'], name='reviews_rev_apartme_4c0ea6_idx'), models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_35ef9b_idx'), models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx')],
                'unique_together': {('user', 'apartment')},
            },
        ),
    ]
