# Generated by Django 6.0.3 on 2026-04-13 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='The original text before translation', verbose_name='original text')),
                ('language', models.CharField(help_text="Target language code (e.g., 'fr', 'sw')", max_length=10, verbose_name='language')),
                ('translated_text', models.TextField(help_text='The translated text', verbose_name='translated text')),
                ('source_language', models.CharField(default='en', help_text="Source language code (default: 'en')", max_length=10, verbose_name='source language')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this translation has been used', verbose_name='usage count')),
            ],
            options={
                'verbose_name': 'translated text',
                'verbose_name_plural': 'translated texts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['original_text', 'language'], name='translation_origina_3c6c11_idx'), models.Index(fields=['language', '-created_at'], name='translation_languag_f57ee0_idx')],
                'unique_together': {('original_text', 'language', 'source_language')},
            },
        ),
    ]
