# Generated by Django 6.0.3 on 2026-03-21 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Check-in date', verbose_name='start date')),
                ('end_date', models.DateField(help_text='Check-out date', verbose_name='end date')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the booking period', max_digits=10, verbose_name='total price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the booking', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], help_text='Mobile money provider for payment', max_length=10, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference number from mobile money', max_length=100, null=True, verbose_name='payment reference')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='pending', help_text='Status of the payment verification', max_length=20, verbose_name='payment status')),
                ('phone_number', models.CharField(help_text='Phone number for payment confirmation', max_length=20, verbose_name='phone number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('apartment', models.ForeignKey(help_text='Apartment being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apartments.apartment')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='bookings_bo_user_id_5943d6_idx'), models.Index(fields=['apartment', 'start_date', 'end_date'], name='bookings_bo_apartme_bf3b2d_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'), models.Index(fields=['payment_status'], name='bookings_bo_payment_27706e_idx')],
            },
        ),
    ]
