# Generated by Django 6.0.3 on 2026-04-10 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, help_text='Unique booking code (e.g., STE-234-AB-93)', max_length=50, null=True, verbose_name='booking code'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], help_text='Mobile money provider for payment', max_length=10, null=True, verbose_name='payment method'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_code'], name='bookings_bo_booking_51e913_idx'),
        ),
    ]
