# Generated by Django 6.0.3 on 2026-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_code_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='TEMP-000', help_text='Unique booking code (e.g., STE-234-AB-93)', max_length=50, unique=True, verbose_name='booking code'),
            preserve_default=False,
        ),
    ]
